sudo: required
services:
    - docker
before_install:
    - docker build -t amoldesai8/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true amoldesai8/docker-react npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-231116518884"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: 
        secure: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"